import Image from "next/image";
import { CTAForm, Footer, Navbar, PillLink } from "@/components/site";

export const metadata = { title: "Why We Built This | AV / Photographer Growth", description: "A more considered way for established wedding photographers to be discovered by the right couples." };

export default function AboutPage() {
  return <main>
    <Navbar />
    <section className="about-hero cream"><div className="shell about-hero-grid"><div className="reveal"><p className="eyebrow">Our reason for being</p><h1>Why We Built This<br /><em>for Wedding Photographers</em></h1></div><div className="prose reveal"><p>We kept seeing the same problem with wedding photographers.</p><p>They had great portfolios, years of experience and a strong reputation, but getting new bookings still depended heavily on referrals, Instagram, word of mouth or wedding platforms.</p><p>Those things can work very well, but they are not always consistent.</p><p>We wanted to build a simpler way for good photographers to get their work in front of more of the right couples.</p><p>That is why we created this specifically for wedding photographers.</p></div></div></section>
    <section className="about-image cinematic"><Image src="/images/middle.png" alt="An editorial workspace in warm afternoon light" fill priority sizes="100vw" className="cover" /><div className="grain" /></section>
    <section className="section cream difference" id="approach"><div className="shell"><div className="section-heading reveal"><p className="eyebrow">01 / What makes this different</p><h2>We Start With <em>Your Work</em></h2></div><div className="editorial-split"><div className="prose reveal"><p>Every photographer is different.</p><p>So we don&apos;t believe in using the same approach for everyone.</p><p>We look at what makes your photography different and build everything around that.</p></div><div className="difference-lines reveal"><p>Your style.</p><p>Your pricing.</p><p>Your location.</p><p>Your couples.</p></div></div></div></section>
    <section className="section black goal-section" id="how-it-works"><div className="shell"><p className="eyebrow light">02 / The goal</p><div className="goal-grid"><h2>More Right People<br /><em>Seeing Your Work</em></h2><div className="prose reveal"><p>We are not trying to make you famous online.</p><p>We are not focused on followers or likes.</p><p>We want more couples who genuinely value your work to discover you.</p></div></div><div className="goal-quote reveal"><p>The kind of couples who look at your portfolio and think:</p><blockquote>“This is exactly what we&apos;re looking for.”</blockquote></div></div></section>
    <section className="section cream" id="who-its-for"><div className="shell editorial-split align-center"><div className="reveal"><p className="eyebrow">03 / A considered fit</p><h2>Who We<br /><em>Work With</em></h2></div><div className="prose reveal"><p>We work with photographers who already have a strong body of work and want a more consistent way to grow their business.</p><p>If you are serious about your photography and want more of the right couples finding you, we should talk.</p><PillLink href="#contact" dark>Start a Conversation</PillLink></div></div></section>
    <section className="final-cta cinematic about-cta" id="contact"><Image src="/images/footer.png" alt="A welcoming creative studio in warm light" fill sizes="100vw" className="cover footer-image" /><div className="footer-shade" /><div className="grain" /><div className="shell cta-grid"><div className="cta-copy reveal"><p className="eyebrow light">The next chapter</p><h2>Your next great client<br />should be able to <em>find you.</em></h2><p>Tell us about the work you create and the weddings you would love to photograph next.</p></div><CTAForm buttonLabel="Start a Conversation" /></div></section>
    <Footer />
  </main>;
}
